// MARK: - Saudi Academies Data
struct SaudiAcademy {
    let name: String
    let city: String
    let street: String
}

let SAUDI_ACADEMIES: [SaudiAcademy] = [
    SaudiAcademy(name: "عين الحياة الرياضي النسائي", city: "تبوك", street: "المهرجان 1"),
    SaudiAcademy(name: "اكاديمية سما المواهب الرياضية", city: "الرياض", street: "فرطبه"),
    SaudiAcademy(name: "اكاديمية سما المواهب الرياضية", city: "الرياض", street: "المربع"),
    SaudiAcademy(name: "طلائع سما", city: "الرياض", street: "ظهرة البديعة"),
    SaudiAcademy(name: "أكاديمية النجوم المضيئة", city: "القطيف", street: "المجيدية - حي المستودعات"),
    SaudiAcademy(name: "اكاديمية الفنرز", city: "المدينة المنورة", street: "ذو الحليفة"),
    SaudiAcademy(name: "ميدان صهوة هدب للتدريب الفروسية", city: "الخبر", street: "حي العقيق"),
    SaudiAcademy(name: "اكاديمية صهوة هدب للفروسية", city: "الدرعية", street: "العمارية"),
    SaudiAcademy(name: "اكادمية نجوم الكرة السوداء", city: "جازان", street: "الروابي"),
    SaudiAcademy(name: "إكاديمية الحوسي للفروسية", city: "حفر الباطن", street: "الاسطبلات القديمه"),
    SaudiAcademy(name: "نجوم الجنوب الرياضي", city: "تثليث", street: "الغزالة"),
    SaudiAcademy(name: "أكاديميه بي ون الرياضيه", city: "البكيرية", street: "حي شرق البكيريه"),
    SaudiAcademy(name: "اكاديمية النجم الرياضيه", city: "القيصومه", street: "الزهور"),
    SaudiAcademy(name: "اكادمية السفير", city: "المدينة المنورة", street: "حي شوران"),
    SaudiAcademy(name: "سيلاريمو", city: "جدة", street: "جدة حى الريان"),
    SaudiAcademy(name: "أكاديمية نجوم الحركة الرياضية", city: "عرعر", street: "حي المباركية"),
    SaudiAcademy(name: "ستار ون", city: "جازان", street: "المطار"),
    SaudiAcademy(name: "أكاديمية وفاق الجنوب الرياضية", city: "أحد رفيدة", street: "المدينة العسكرية"),
    SaudiAcademy(name: "مؤسسة غيوم الرياضية", city: "محايل", street: "الحيلة الشرقى"),
    SaudiAcademy(name: "فري زون", city: "البكيرية", street: "المجد"),
    SaudiAcademy(name: "أحلام النورس", city: "أحد المسارحة", street: "البلدية"),
    SaudiAcademy(name: "أكاديمية نيو", city: "الرياض", street: "حى السعادة"),
    SaudiAcademy(name: "أكاديمية السباح الذهبي الرياضي", city: "جدة", street: "المحمدية"),
    SaudiAcademy(name: "أكاديمية المطوع", city: "الرياض", street: "القادسية"),
    SaudiAcademy(name: "اكاديمية دايفينق سيكريت للسباحة", city: "الرياض", street: "النخيل"),
    SaudiAcademy(name: "أكاديمية ريمونتادا", city: "الرياض", street: "عكاظ"),
    SaudiAcademy(name: "العالم الرياضية", city: "جدة", street: "النهضة"),
    SaudiAcademy(name: "الظهران", city: "الدمام", street: "الندى"),
    SaudiAcademy(name: "أكاديمية أصيل العرب الرياضي", city: "صبيا", street: "الجحيين"),
    SaudiAcademy(name: "اكاديميه فاست وان", city: "الرياض", street: "الرمال"),
    SaudiAcademy(name: "أكاديمية الأآغن للخيل العربية الأصيلة", city: "البصر", street: "المليداء"),
    SaudiAcademy(name: "تنس بلس", city: "الدمام", street: "الصفا"),
    SaudiAcademy(name: "اكاديميه فاست وان", city: "الرياض", street: "الربيع"),
    SaudiAcademy(name: "اكاديميه فاست وان", city: "الرياض", street: "المصيف"),
    SaudiAcademy(name: "أكاديمية المجد النموذجية الرياضية", city: "جدة", street: "الشراع"),
    SaudiAcademy(name: "أكاديمية جوالدن الرياضية2", city: "جدة", street: "المنار"),
    SaudiAcademy(name: "اكاديمية سما المواهب الرياضية", city: "الرياض", street: "الملقا"),
    SaudiAcademy(name: "اكاديمية سما المواهب الرياضية", city: "الرياض", street: "النزهة"),
    SaudiAcademy(name: "اكاديمية سما المواهب الرياضية", city: "الرياض", street: "المغرزات"),
    SaudiAcademy(name: "اكاديمية سما المواهب الرياضية", city: "الرياض", street: "ظهرة لبن"),
    SaudiAcademy(name: "أكاديمية ليبرو ارساطية", city: "بيش", street: "السلام"),
    SaudiAcademy(name: "أكاديمية نهم الرياضية", city: "بيش", street: "السلام"),
    SaudiAcademy(name: "مركز الغزاوي للفروسية", city: "جدة", street: "ام حيلين"),
    SaudiAcademy(name: "أكاديمية البشائر الاولى الرياضية", city: "بلقرن", street: "البشائر"),
    SaudiAcademy(name: "شارك الابطال", city: "الرياض", street: "النهضه"),
    SaudiAcademy(name: "اواكس", city: "الخبر", street: "الكورنيش"),
    SaudiAcademy(name: "اكاديمية الجفن الدولية الرياضية", city: "بريدة", street: "النفع"),
    SaudiAcademy(name: "أكاديميات الرؤية السعوديه الرياضه", city: "جدة", street: "النهضه"),
    SaudiAcademy(name: "أكاديمية نادي غزال للتيكوندو", city: "مكة المكرمة", street: "النزهة"),
    SaudiAcademy(name: "أكاديمية ليوث تهامه", city: "محايل", street: "فنا"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - البيرموك", city: "الرياض", street: "القادسية"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - الحزم", city: "الرياض", street: "الحزم"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - مدارس الملك فيصل", city: "الرياض", street: "السفارات"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - النقل", city: "الرياض", street: "النقل"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - القيروان", city: "الرياض", street: "القيروان"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - الريان", city: "الرياض", street: "الريان"),
    SaudiAcademy(name: "فرع المملكة - سباحة", city: "الرياض", street: "الربيع"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - فرع جدة", city: "جدة", street: "المحمدية"),
    SaudiAcademy(name: "فرع النزهة - كرة قدم", city: "الرياض", street: "النزهة"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - مدارس التربية النموذجية فرع العارض", city: "الرياض", street: "العارض"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - مدارس منارات الرياض", city: "الرياض", street: "الازدهار"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - فرع الدمام", city: "الدمام", street: "الحمراء"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - الياسمين", city: "الرياض", street: "الياسمين"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - مدارس المملكة", city: "الرياض", street: "الربيع"),
    SaudiAcademy(name: "أكاديمية نادي الهلال - عرفة", city: "الرياض", street: "عرفة"),
    SaudiAcademy(name: "أكاديميه فاست وان الرياضيه", city: "الرياض", street: "الخليج"),
    SaudiAcademy(name: "ميدان ريف المنال للفروسية", city: "الدمام", street: "غرب المطار"),
    SaudiAcademy(name: "الريشة الطائرة", city: "الدمام", street: "الخالدية الجنوبية"),
    SaudiAcademy(name: "أكاديمية روبازر الرياضية", city: "الرياض", street: "وادي لبن"),
    SaudiAcademy(name: "أكاديمية بيت التنس", city: "الرياض", street: "النرجس"),
    SaudiAcademy(name: "باليرمو", city: "المدينة المنورة", street: "حي شظاة"),
    SaudiAcademy(name: "أكاديمية بيت التنس", city: "الرياض", street: "النرجس"),
    SaudiAcademy(name: "اكاديمية حلم النجوم الرياضية", city: "الرس", street: "الملك خالد"),
    SaudiAcademy(name: "أكاديمية بحرة", city: "مكة المكرمة", street: "بحره"),
    SaudiAcademy(name: "أكاديمية اشبيلية المدينة الرياضية", city: "المدينة المنورة", street: "حي الازهري"),
    SaudiAcademy(name: "اكاديمية الساميا الرياضية", city: "جدة", street: "البدر"),
    SaudiAcademy(name: "أكاديمية روني أوسوليغان للسنوكر", city: "الرياض", street: "حي حطبين - بوليفارد رياض سيتي"),
    SaudiAcademy(name: "أكاديميات أبطال النخبة الرياضية", city: "الخبر", street: "الكوثر"),
    SaudiAcademy(name: "ستارز أكاديمية التربية الرياضية-الروابي", city: "الرياض", street: "الروابي"),
    SaudiAcademy(name: "ستارز أكاديمية التربية الرياضية-النزهة", city: "الرياض", street: "النزهة"),
    SaudiAcademy(name: "أكاديمية نخبة الحمدالية الرياضيه", city: "جدة", street: "الحمدانية"),
    SaudiAcademy(name: "جدة سيتي", city: "جدة", street: "النعيم"),
    SaudiAcademy(name: "غيوم الرياضية بمحايل", city: "محايل", street: "الحيلة الشرقي"),
    SaudiAcademy(name: "نجوم مجد", city: "الطائف", street: "مسيرة"),
    SaudiAcademy(name: "تيم قول", city: "الباحة", street: "حي الباهر"),
    SaudiAcademy(name: "أكاديمية الفذ", city: "الرياض", street: "المصانع"),
    SaudiAcademy(name: "أكاديمية أشبال البراعم الرياضي", city: "الدمام", street: "الشاطئ الغربي"),
    SaudiAcademy(name: "أكاديمية المستقبل للرياضه", city: "الخبر", street: "اليرموك"),
    SaudiAcademy(name: "اكاديمية ساحة التحدى", city: "جدة", street: "الرحاب"),
    SaudiAcademy(name: "مركز عنان للفروسية", city: "الدرعية", street: "العمارية"),
    SaudiAcademy(name: "ميدان مسار الفروسية للفروسية", city: "المجمعة", street: "حرمة"),
    SaudiAcademy(name: "اساس الرياضة الرياضي", city: "الرياض", street: "النرجس"),
    SaudiAcademy(name: "أكاديمية القمة الرياضية", city: "جدة", street: "الزهراء"),
    SaudiAcademy(name: "اكاديمية فيصل الدخيل الرياضية", city: "حفر الباطن", street: "التلال"),
    SaudiAcademy(name: "اكاديمية الصواري للخيل العربية الاصيله", city: "جدة", street: "ام حيلين"),
    SaudiAcademy(name: "أكاديمية بلو", city: "الجبيل", street: "جلمودة"),
    SaudiAcademy(name: "نادي نجوم المنافسين الرياضي", city: "رفحا", street: "الربيع"),
    SaudiAcademy(name: "أكاديمية المحترفين الأوائل لتعليم كرة القدم", city: "حائل", street: "حي الزهرة"),
    SaudiAcademy(name: "أكاديمية مستقبل الأبطال الرياضية", city: "الرياض", street: "الفيحاء"),
    SaudiAcademy(name: "أكاديميه الزعـــــــيم الرياضية", city: "جازان", street: "حي الشواجرة"),
    SaudiAcademy(name: "أكاديمية", city: "الجبيل", street: "جلمودة"),
    SaudiAcademy(name: "أكاديمية سيورتس الرياضية", city: "الرياض", street: "حي الفيحاء"),
    SaudiAcademy(name: "أكاديمية الفهد الرياضية", city: "المدينة المنورة", street: "الملك فهد"),
    SaudiAcademy(name: "شارك", city: "الرياض", street: "اشبيلية"),
    SaudiAcademy(name: "أكاديمية جدة سنايبر", city: "جدة", street: "الروضة"),
    SaudiAcademy(name: "نادي نجوم خزاز", city: "دخنة", street: "السلام"),
    SaudiAcademy(name: "أكاديمية السيسبان الرياضية", city: "المندق", street: "العدل"),
    SaudiAcademy(name: "أكاديمية الجوكر الرياضية", city: "الرياض", street: "بحر"),
    SaudiAcademy(name: "أكاديمية الرواد الرياضية", city: "جدة", street: "الزهراء"),
    SaudiAcademy(name: "مركز منيرا للخيول", city: "الرياض", street: "عرفة"),
    SaudiAcademy(name: "أكاديمية ميدان الهوايات الاحترافية للفروسية", city: "الرياض", street: "ظهرة لبن"),
    SaudiAcademy(name: "منتجع الفروسية العالمى", city: "الرياض", street: "لبن"),
    SaudiAcademy(name: "أكاديمية بيت التنس", city: "الرياض", street: "حي الملك فهد"),
    SaudiAcademy(name: "أكاديمية فارس", city: "الرياض", street: "قرطبة"),
    SaudiAcademy(name: "أكاديمية عروس الربع الغالي", city: "شرورة", street: "سلطانه 6746, شرورة 68372"),
    SaudiAcademy(name: "أكاديمية عروس الربع الغالي الرياضية", city: "شرورة", street: "سلطانه"),
    SaudiAcademy(name: "أكاديمية منارة الرياضة", city: "جدة", street: "الزهراء"),
    SaudiAcademy(name: "مركز شباب الصحراء الرياضي (اكاديمية الصحراء)", city: "العقيق", street: "الغوث"),
    SaudiAcademy(name: "ستارز أكاديمية التربية الرياضية-الريان", city: "الرياض", street: "الريان"),
    SaudiAcademy(name: "أكاديمية سهم الدرب الرياضية", city: "الدرب", street: "الدرب القديم"),
    SaudiAcademy(name: "أكاديمية الشروق الرياضية", city: "نجران", street: "دحضه"),
    SaudiAcademy(name: "قاموس", city: "الرياض", street: "قرطبة"),
    SaudiAcademy(name: "مواهب اسبار", city: "حفر الباطن", street: "الربوه"),
    SaudiAcademy(name: "أكاديمية موسم السرعة", city: "الرياض", street: "الازدهار"),
    SaudiAcademy(name: "أكاديمية فيوتشر هورس", city: "وادي جازان", street: "الواسط"),
    SaudiAcademy(name: "أكاديمية المحامل للفروسية", city: "أحد المسارحة", street: "المحامل"),
    SaudiAcademy(name: "أكاديمية العماد للفروسية", city: "رابغ", street: "طريق البحر"),
    SaudiAcademy(name: "أكاديمية لاجونا لركوب الخيل", city: "رابغ", street: "مدينة الملك عبدالله الاقتصادية- حى رسيل"),
    SaudiAcademy(name: "شهم", city: "الرياض", street: "النهضة"),
    SaudiAcademy(name: "شهم", city: "الرياض", street: "النهضة"),
    SaudiAcademy(name: "مواهب الكره", city: "جدة", street: "طيبة"),
    SaudiAcademy(name: "أكنف تايم", city: "الرياض", street: "الربيع"),
    SaudiAcademy(name: "أكاديمية اكنف تايم للكارانيه", city: "الرياض", street: "الربيع"),
    SaudiAcademy(name: "أكاديمية نخبة الخيل الرياضية", city: "الدرعية", street: "حى الدرعية الجديد"),
    SaudiAcademy(name: "أكاديمية قلب الاسد الرياضية", city: "جازان", street: "الرحاب"),
    SaudiAcademy(name: "أكاديمية الكسير للسباحة", city: "بريدة", street: "الصفراء"),
    SaudiAcademy(name: "اكاديمية الفارس", city: "الرياض", street: "حي التعاون"),
    SaudiAcademy(name: "الوان الحركة", city: "الرياض", street: "الياسمين"),
    SaudiAcademy(name: "أكاديمية المرجان الأزرق الرياضي", city: "جدة", street: "الحمراء"),
    SaudiAcademy(name: "أكاديمية لبن فور الرياضية", city: "جدة", street: "الزهراء"),
    SaudiAcademy(name: "جدة يونايتد", city: "جدة", street: "حي الشاطىء"),
    SaudiAcademy(name: "أكاديمية إيباري للخيل العربية الاصيلة", city: "عقلة الصقور", street: "الريان"),
    SaudiAcademy(name: "أكاديمية صهباء للفروسية", city: "جدة", street: "أم حيلين"),
    SaudiAcademy(name: "أكاديمية مواهب الاشبال الرياضية", city: "الرياض", street: "عكاظ"),
    SaudiAcademy(name: "دار سعد للفروسية", city: "الأحساء", street: "الوزية"),
    SaudiAcademy(name: "نادي سعد بن عبدالعزيز بن سعد القنبر للفروسيه", city: "الأحساء", street: "الوزية"),
    SaudiAcademy(name: "مركز عز الشامخ للخيل العربية الاصيلة", city: "الرياض", street: "دبراب"),
    SaudiAcademy(name: "أكاديمية المجد النموذجية الرياضية", city: "جدة", street: "الشراع"),
    SaudiAcademy(name: "أكاديمية المدرسة الماسية", city: "جدة", street: "الامير فواز الجنوبي"),
    SaudiAcademy(name: "برشاء", city: "الرياض", street: "قرطبة"),
    SaudiAcademy(name: "اكاديمية مذهلة للفروسية", city: "بريدة", street: "الهجدية الشمالية"),
    SaudiAcademy(name: "أكاديمية ميادين للفروسية", city: "الرياض", street: "بنيان"),
    SaudiAcademy(name: "أكاديمية مواهب الدمام", city: "الدمام", street: "الفيصلية"),
    SaudiAcademy(name: "أكاديمية فارس", city: "الرياض", street: "الحمراء"),
    SaudiAcademy(name: "أكاديمية فارس", city: "الرياض", street: "النزهة"),
    SaudiAcademy(name: "أكاديمية فارس", city: "الطائف", street: "ج 1"),
    SaudiAcademy(name: "أكاديمية فارس", city: "حائل", street: "النقرة"),
    SaudiAcademy(name: "أكاديمية فارس", city: "الرياض", street: "الصحافة"),
    SaudiAcademy(name: "أكاديمية فارس", city: "الرياض", street: "الأندلس"),
    SaudiAcademy(name: "أكاديمية فارس", city: "الرياض", street: "العارض"),
    SaudiAcademy(name: "أكاديمية فارس", city: "الرياض", street: "الغدير"),
    SaudiAcademy(name: "اكاديمية نخية", city: "الطائف", street: "مثملة"),
    SaudiAcademy(name: "خالد عبدالعزيز عبدالله العيد", city: "الرياض", street: "الجناديرية"),
    SaudiAcademy(name: "أكاديمية السباحة الأولى الرياضية", city: "جدة", street: "الحمراء"),
    SaudiAcademy(name: "رامة للفروسية", city: "الدرعية", street: "العمارية"),
    SaudiAcademy(name: "أكاديمية مجتمعى لكرة القدم", city: "المدينة المنورة", street: "الخالدية"),
    SaudiAcademy(name: "أكاديمية النبلاء القوباء", city: "الرياض", street: "الملك عبدالله"),
    SaudiAcademy(name: "أكاديمية فارس", city: "الرياض", street: "الازدهار"),
    SaudiAcademy(name: "أكاديمية فارس", city: "الرياض", street: "النرجس"),
    SaudiAcademy(name: "أكاديمية فارس", city: "خميس مشيط", street: "درة النسك"),
    SaudiAcademy(name: "أكاديمية الفقر والتوازن الرياضية", city: "جدة", street: "النهضة"),
    SaudiAcademy(name: "المدرسة الاسبانية", city: "جدة", street: "الشراع"),
    SaudiAcademy(name: "المدرسة الاسبانية", city: "جدة", street: "الفيصلية"),
    SaudiAcademy(name: "أكاديمية رياضة التايكوندو", city: "الدمام", street: "العنود"),
    SaudiAcademy(name: "اكاديمية اجيال الرياضية", city: "الدمام", street: "الصدفية الراكة"),
    SaudiAcademy(name: "أكاديمية يوفينتوس", city: "الخبر", street: "الراكة"),
    SaudiAcademy(name: "أكاديمية فوارس الجزيرة الرياضية", city: "الدمام", street: "طيبة"),
    SaudiAcademy(name: "اكاديمية ستار ون الرياضية", city: "جازان", street: "المطار"),
    SaudiAcademy(name: "وقت الكرة", city: "الرياض", street: "طويق"),
    SaudiAcademy(name: "مواهب المجد الرياضية", city: "الرياض", street: "اشبيلية"),
    SaudiAcademy(name: "أكاديمية التنس والاحتراف الرياضية", city: "جدة", street: "الشراع"),
    SaudiAcademy(name: "النسر الماسى", city: "الخبر", street: "حى الصدفة"),
    SaudiAcademy(name: "ذا ريك", city: "القطيف", street: "القدحيج"),
    SaudiAcademy(name: "الرياضة للحياه", city: "الرياض", street: "السفارات"),
    SaudiAcademy(name: "أكاديمية منارة الرياضة", city: "جدة", street: "الزهراء"),
    SaudiAcademy(name: "أكاديمية مهارة لاعب الرياضية", city: "الفوارة", street: "النهضة"),
    SaudiAcademy(name: "القدية للفروسية", city: "المراحمية", street: "هدلولة"),
    SaudiAcademy(name: "أكاديمية المبدع", city: "المدينة المنورة", street: "حي السد"),
    SaudiAcademy(name: "أكاديمية الفيتو", city: "المدينة المنورة", street: "حي السد"),
    SaudiAcademy(name: "اكاديمية سبورت360", city: "المدينة المنورة", street: "ذو الحليفة"),
    SaudiAcademy(name: "أكاديمية مواهب المحترفين الرياضية", city: "الرياض", street: "اشبيلية"),
    SaudiAcademy(name: "أكاديمية سيورتس", city: "الرياض", street: "حي النرجس"),
    SaudiAcademy(name: "أكاديمية سيورتس الرياضية", city: "الرياض", street: "حي المغرزات"),
    SaudiAcademy(name: "الضفر الجارح", city: "أحد رفيدة", street: "النهضة"),
    SaudiAcademy(name: "اكاديمية نجوم تهامة", city: "المجاردة", street: "الروضة"),
    SaudiAcademy(name: "أكوافالكون", city: "الرياض", street: "قرطبة"),
    SaudiAcademy(name: "نوفا للفروسية", city: "الرياض", street: "خبيب الريم"),
    SaudiAcademy(name: "روبوتينك", city: "الظهران", street: "حي القصور"),
    SaudiAcademy(name: "أكاديمية الولاء الرياضية", city: "الدمام", street: "البحيرة"),
    SaudiAcademy(name: "أكاديمية الأبطال", city: "الجبيل", street: "البحر"),
    SaudiAcademy(name: "نادي الفرسان الرياضي", city: "سراة عبيدة", street: "الشفا"),
    SaudiAcademy(name: "اتحاد العزم", city: "الأحساء", street: "جواثا"),
    SaudiAcademy(name: "اكاديمية الراية", city: "الرياض", street: "القادسية"),
    SaudiAcademy(name: "بلاتنيوم", city: "جدة", street: "الخالدية"),
    SaudiAcademy(name: "أكاديمية درة الرياضة", city: "رياض الخبراء", street: "النفيد"),
    SaudiAcademy(name: "أكاديمية الصارم البتار الرياضية", city: "الرياض", street: "الجناديرية"),
    SaudiAcademy(name: "أكاديمية باسكت ان", city: "الرياض", street: "التعاون"),
    SaudiAcademy(name: "أكاديمية مهارة الاحتراف الرياضي", city: "الطائف", street: "الواسط"),
    SaudiAcademy(name: "أكاديميه المايسترو الرياضيه", city: "الرياض", street: "العزيزيه"),
    SaudiAcademy(name: "أكاديمية أمل السودان", city: "الرياض", street: "صباح"),
    SaudiAcademy(name: "أمل السودان", city: "حائل", street: "النقرة"),
    SaudiAcademy(name: "أكاديمية القصيم الرياضية", city: "البدائع", street: "طيبة"),
    SaudiAcademy(name: "المواهب", city: "الرياض", street: "لبن"),
    SaudiAcademy(name: "أكاديمية امبراطور الرياضية", city: "المدينة المنورة", street: "قربان"),
    SaudiAcademy(name: "أكاديمية النوفاوي", city: "مكة المكرمة", street: "الراشدية"),
    SaudiAcademy(name: "أكاديمية دايموند", city: "الرياض", street: "عرفة"),
    SaudiAcademy(name: "أكاديمية دايموند", city: "الرياض", street: "المهدية"),
    SaudiAcademy(name: "أكاديمية قوة الفرسان الرياضية", city: "أحد رفيدة", street: "حي الخليج"),
    SaudiAcademy(name: "أكاديمية أيرون بوكس للسباحة", city: "الخفجي", street: "العزيزية"),
    SaudiAcademy(name: "الجزيره", city: "الرياض", street: "عريجا الوسطى"),
    SaudiAcademy(name: "بادل بلوك", city: "الهفوف", street: "السيقة"),
    SaudiAcademy(name: "نوادي الريم الرياضية", city: "تبوك", street: "الفيصلية الشمالية"),
    SaudiAcademy(name: "توفيت اللياقة", city: "عفيف", street: "النهضه"),
    SaudiAcademy(name: "نوادي الريم الرياضية", city: "تبوك", street: "الفيصلية الشمالية"),
    SaudiAcademy(name: "نادي النخبة المتميزة للفروسية", city: "جدة", street: "ام حيلين"),
    SaudiAcademy(name: "أكاديمية مواهب بيشة الأولى", city: "بيشة", street: "حي الفهد"),
    SaudiAcademy(name: "سان جدة", city: "مكة المكرمة", street: "الصفا"),
    SaudiAcademy(name: "أكاديميه ارتي", city: "الرياض", street: "المروة"),
    SaudiAcademy(name: "أكاديميه الدائر", city: "بني مالك", street: "المضيعه"),
    SaudiAcademy(name: "اكاديمية الفيفا المتحدة الرياضية", city: "الرياض", street: "الريوة"),
    SaudiAcademy(name: "أكاديمية المحترف عشرين الرياضية", city: "حبونا", street: "حبونا"),
    SaudiAcademy(name: "ستار سفن", city: "بيشة", street: "الموطي"),
    SaudiAcademy(name: "معهد ذا بيلانس استوديو", city: "الرياض", street: "قرطبة"),
    SaudiAcademy(name: "أكاديميه نادي الشباب", city: "الرياض", street: "حسـى اليمامه"),
    SaudiAcademy(name: "أكاديمية مستقبل المحترفين الرياضية", city: "الرياض", street: "القيروان"),
    SaudiAcademy(name: "ميدان دبراب", city: "الرياض", street: "ضاحية النمار"),
    SaudiAcademy(name: "أكاديمية الذات الرياضية", city: "جدة", street: "العزيزية"),
    SaudiAcademy(name: "أكاديمية أجيال الحياة الرياضي", city: "الجوف", street: "شرق اللقائط"),
    SaudiAcademy(name: "الفيروز للخيل العربية الاصيلة", city: "الطائف", street: "الحوية"),
    SaudiAcademy(name: "المطرف الرياضية", city: "الرياض", street: "ظهرة نمار"),
    SaudiAcademy(name: "أكاديمية مواهب جدة الرياضية", city: "جدة", street: "الفلاح ا"),
    SaudiAcademy(name: "أكاديمية مواهب جده", city: "جدة", street: "الفلاح"),
    SaudiAcademy(name: "أكاديمية نت للتنس", city: "الدرعية", street: "الدرعية الجديدة"),
    SaudiAcademy(name: "مواهب أرينا", city: "الرياض", street: "الحزم"),
    SaudiAcademy(name: "ساحة الشرارة الرياضي", city: "تاروت", street: "الجوهرة"),
    SaudiAcademy(name: "أكاديمية بلاك ستارز", city: "الرياض", street: "صباح"),
    SaudiAcademy(name: "أكاديمية الأوائل الرياضية", city: "الرياض", street: "العريجاء"),
    SaudiAcademy(name: "أكاديمية نجم الجبل الرياضية", city: "ينبع", street: "الجابرية"),
    SaudiAcademy(name: "نادي جدة لليخوت", city: "جدة", street: "الشاطئ"),
    SaudiAcademy(name: "اسطيل خالد مبارك للخيول", city: "الخبر", street: "السفن"),
    SaudiAcademy(name: "أكاديمية القلعة الرياضية", city: "خميس مشيط", street: "شباعة"),
    SaudiAcademy(name: "أكاديمية خالد مبارك الدحيم", city: "الخبر", street: "اليرموك"),
    SaudiAcademy(name: "أكاديمية فنون أسيا للدفاع عن النفس", city: "جدة", street: "الفيصلية"),
    SaudiAcademy(name: "اتحاد الفرسان الرياضية", city: "الجبيل", street: "الحويلات"),
    SaudiAcademy(name: "أكاديمية جامعة الأمير محمد بن فهد الرياضيه", city: "الظهران", street: "الظهران"),
    SaudiAcademy(name: "ميسان", city: "الظهران", street: "الظهران"),
    SaudiAcademy(name: "أكاديمية الفيصل للفروسية", city: "أبها", street: "المطار"),
    SaudiAcademy(name: "اسطبل الفارسة النسائي", city: "الرياض", street: "الزمال اسطبلات الخيل"),
    SaudiAcademy(name: "أكاديمية ابطال البيداء الرياضي", city: "المدينة المنورة", street: "العزيزية"),
    SaudiAcademy(name: "أكاديمية مدهال للفروسية", city: "الرياض", street: "حي الزمال"),
    SaudiAcademy(name: "أكاديمية موهوب", city: "الرياض", street: "القيروان"),
    SaudiAcademy(name: "أكاديمية ضوء القمر الرياضية", city: "الخبر", street: "المها - العزيزية"),
    SaudiAcademy(name: "أكاديميه سعودي سمارت", city: "جدة", street: "الاجاويد"),
    SaudiAcademy(name: "أكاديمية سمارت فونبول الرياضية", city: "جدة", street: "الاجاويد"),
    SaudiAcademy(name: "كرة النجوم", city: "مكة المكرمة", street: "الحسينية"),
    SaudiAcademy(name: "أكاديمية فاست فت", city: "الرياض", street: "الورود"),
    SaudiAcademy(name: "النجم", city: "حفر الباطن", street: "التلال"),
    SaudiAcademy(name: "أكاديمية ذهبي الرياضية", city: "الدمام", street: "الشاطئ"),
    SaudiAcademy(name: "تريس", city: "الدمام", street: "الشاطئ الغربي"),
    SaudiAcademy(name: "أكاديمية الفناص", city: "نجران", street: "حي الأثابية"),
    SaudiAcademy(name: "أكاديمية أفق للباركور", city: "الرياض", street: "النرجس"),
    SaudiAcademy(name: "شركة خطوات المسار الرياضية", city: "الرياض", street: "وادي حنيفه"),
    SaudiAcademy(name: "شركة خطوات المسار الرياضية", city: "الرياض", street: "وادي حنيفه"),
    SaudiAcademy(name: "أكاديمية اللاعب الموهوب للرياضة", city: "القطيف", street: "المجيدية"),
    SaudiAcademy(name: "أكاديمية اكتشفني الرياضية", city: "الرياض", street: "عكاظ"),
    SaudiAcademy(name: "اكاديمية الروح الرياضية", city: "الرياض", street: "القيروان"),
    SaudiAcademy(name: "أكاديمية الشكل الرياضية", city: "الرياض", street: "النظيم"),
    SaudiAcademy(name: "أكاديمية اسود الخيل الرياضية", city: "الدمام", street: "البحر"),
    SaudiAcademy(name: "أكاديمية تربو", city: "جدة", street: "بريمان"),
    SaudiAcademy(name: "أكاديمية مواهب الخليج الرياضية", city: "سيهات", street: "الديرة"),
    SaudiAcademy(name: "أكاديمية نسعين الرياضية", city: "الدمام", street: "المنار"),
    SaudiAcademy(name: "أكاديمية اتقان الهدف الرياضية", city: "الفويعة", street: "المروج"),
    SaudiAcademy(name: "ملعب وأكاديمية الوداد الطائفي", city: "الطائف", street: "المثناة"),
    SaudiAcademy(name: "أكاديمية الابطال القادمين الرياضية", city: "الرياض", street: "النرجس"),
    SaudiAcademy(name: "أبار", city: "جازان", street: "الشاطي"),
    SaudiAcademy(name: "أكاديمية الهدف الاحترافي", city: "الرياض", street: "العارض"),
    SaudiAcademy(name: "مريط ابن زحيفة للفروسية", city: "خميس مشيط", street: "حي الرونة"),
    SaudiAcademy(name: "نجمة جدة", city: "جدة", street: "الاجاويد"),
    SaudiAcademy(name: "أكاديمية مهارات المواهب الرياضية", city: "البدائع", street: "اليرموك"),
    SaudiAcademy(name: "أكاديمية عبدالجليل بن أحمد بن عبدالعزيز زين الدين", city: "سيهات", street: "الكوثر"),
    SaudiAcademy(name: "أكاديمية كرة القدم تراك جم", city: "مكة المكرمة", street: "ولي العهد"),
    SaudiAcademy(name: "المدرسة السعودية الالمانية", city: "الرياض", street: "السعادة"),
    SaudiAcademy(name: "اكاديمية صناع الاحتراف", city: "الرياض", street: "السعادة"),
    SaudiAcademy(name: "وصال الخير", city: "جدة", street: "ام حيلين"),
    SaudiAcademy(name: "أكاديمية ارنس فونبول", city: "الخرج", street: "اليمامه"),
    SaudiAcademy(name: "اللواء الأسود", city: "الأحساء", street: "حي نادي الفروسيه"),
    SaudiAcademy(name: "أكاديمية موهبة الرياضة", city: "بريدة", street: "النور"),
    SaudiAcademy(name: "أكاديمية شاطئ الشباب الرياضية", city: "جازان", street: "حي الصناعية"),
    SaudiAcademy(name: "أكاديمية نجوم زمن الرياضي", city: "الطائف", street: "حي الكدى"),
    SaudiAcademy(name: "القرية الأولمبية", city: "جدة", street: "العزيزية"),
    SaudiAcademy(name: "أكاديمية الرمحا للفروسية", city: "الرياض", street: "بنيان"),
    SaudiAcademy(name: "أكاديمية ليو", city: "الأحساء", street: "الجابريه"),
    SaudiAcademy(name: "أكاديمية فخر", city: "الدمام", street: "حي المنار"),
    SaudiAcademy(name: "اكاديمية محترف نجد الرياضية", city: "عنيزة", street: "الوفاء"),
    SaudiAcademy(name: "أكاديمية الأرض السعيدة الرياضية", city: "الخبر", street: "اليرموك"),
    SaudiAcademy(name: "أكاديمية ليدرز", city: "الرياض", street: "السعادة"),
    SaudiAcademy(name: "أي تو جيم", city: "الخرج", street: "غرناطة"),
    SaudiAcademy(name: "أكاديمية المواهب", city: "سكاكا", street: "الصالحية"),
    SaudiAcademy(name: "مركز قمة الهدوء الرياضي", city: "الرياض", street: "حي الياسمين"),
    SaudiAcademy(name: "مؤسسة العيبها صح الرياضية", city: "الرياض", street: "العزيزية"),
    SaudiAcademy(name: "أكاديمية الأبطال الدوليين الرياضية", city: "الجبيل", street: "المرقاب"),
    SaudiAcademy(name: "ليب رو", city: "الدائر", street: "الصدارة"),
    SaudiAcademy(name: "أكاديمية الضربة العالمية الرياضية", city: "الدمام", street: "الاسكان"),
    SaudiAcademy(name: "أكاديمية الرياضات الهوائية", city: "جدة", street: "الشاطئ"),
    SaudiAcademy(name: "نادي الاصائل للفروسية", city: "العارضة", street: "الجوة"),
    SaudiAcademy(name: "اكاديمية المملكة", city: "جدة", street: "الفيصلية"),
    SaudiAcademy(name: "أكاديمية المملكة", city: "جدة", street: "الشراع"),
    SaudiAcademy(name: "أكاديمية الرواد الرياضية", city: "خميس مشيط", street: "المطار"),
    SaudiAcademy(name: "شركة الرياضات المالية العربية للمعدات الرياضية", city: "جدة", street: "King Abdullah Economic City"),
    SaudiAcademy(name: "شركة الرياضات المالية العربية للمعدات الرياضية", city: "جدة", street: "King Abdullah Economic City"),
    SaudiAcademy(name: "أجيال الأبطال", city: "مكة المكرمة", street: "حي الحمزاء وأم الجود"),
    SaudiAcademy(name: "أهداف الكرة", city: "الأحساء", street: "الشراع الجنوبي"),
    SaudiAcademy(name: "فارس أرينا الرياضية", city: "صمد", street: "المحله"),
    SaudiAcademy(name: "اسطبلات الرياض", city: "الرياض", street: "الجناديرية"),
    SaudiAcademy(name: "أكاديمية الليتك الرياضية", city: "البكيرية", street: "النهضة"),
    SaudiAcademy(name: "رحال التعاون", city: "جدة", street: "الوزيرية"),
    SaudiAcademy(name: "أكاديمية بلبير لكرة القدم", city: "الرياض", street: "بدر"),
    SaudiAcademy(name: "الرؤية المحلزمة", city: "مكة المكرمة", street: "العوالي"),
    SaudiAcademy(name: "الجوهرة", city: "جدة", street: "الجرازات"),
    SaudiAcademy(name: "أسيست", city: "جدة", street: "المرجان"),
    SaudiAcademy(name: "أسيست", city: "الرياض", street: "المصانع"),
    SaudiAcademy(name: "اكاديمية نجوم", city: "الخرج", street: "اليمامة"),
    SaudiAcademy(name: "أكاديمية الأصيل الفروسية", city: "جدة", street: "ام حيلن"),
    SaudiAcademy(name: "الأكاديمية السعودية للبيلانيس", city: "الرياض", street: "المروج"),
    SaudiAcademy(name: "أكاديمية وجهة رياضية", city: "الرياض", street: "قرطبية"),
    SaudiAcademy(name: "أكاديمية البانك للمبازرة", city: "الرياض", street: "الشهداء"),
    SaudiAcademy(name: "أكاديمية الفائت للفروسية", city: "ضرماء", street: "المغربية"),
    SaudiAcademy(name: "أكاديمية تالنت", city: "عنيزة", street: "الصيف"),
    SaudiAcademy(name: "أكاديمية باري القوس للفروسية", city: "مكة المكرمة", street: "الحديبية"),
    SaudiAcademy(name: "أكاديمية العين سفن الرياضية", city: "صبيا", street: "حي الطيبة"),
    SaudiAcademy(name: "أكاديمية فو", city: "الزلفي", street: "الروضة"),
    SaudiAcademy(name: "أكاديمية الكأس المتحدة الرياضية", city: "الخرج", street: "الورود"),
    SaudiAcademy(name: "أكاديمية سايار برو المتحدة الرياضية", city: "الخبر", street: "العليا"),
    SaudiAcademy(name: "كرة القدم", city: "مكة المكرمة", street: "المحمدية"),
    SaudiAcademy(name: "أكاديمية لوسيل الرياضية", city: "صبيا", street: "النهفة"),
    SaudiAcademy(name: "أكاديمية الخرج الرياضية", city: "الخرج", street: "حي الورود"),
    SaudiAcademy(name: "أكاديمية ستون ذقيقة", city: "جدة", street: "الزهراء"),
    SaudiAcademy(name: "أكاديمية مواهب الرياضة الرياضية", city: "الرياض", street: "النرجس"),
    SaudiAcademy(name: "النيل", city: "جدة", street: "الاجاويد"),
    SaudiAcademy(name: "النيل", city: "جدة", street: "الاجاويد"),
    SaudiAcademy(name: "الوسام", city: "الرياض", street: "النحزم"),
    SaudiAcademy(name: "أكاديمية سهيل سنار الرياضية", city: "نجران", street: "الثالية"),
    SaudiAcademy(name: "الأكاديمية السعودية الرياضية", city: "الرياض", street: "الزمال"),
    SaudiAcademy(name: "أكاديمية مهد الإحتراج الرياضية", city: "ينبع", street: "الشاطي"),
    SaudiAcademy(name: "أكاديمية أرض النجوم الرياضية", city: "نجران", street: "صاغر"),
    SaudiAcademy(name: "المدرة", city: "مكة المكرمة", street: "الحسينية"),
    SaudiAcademy(name: "أكاديمية فاست وان الرياضية", city: "مكة المكرمة", street: "الزمال"),
    SaudiAcademy(name: "أكاديمية التنية", city: "بيشة", street: "التنية"),
    SaudiAcademy(name: "أكاديمية السيسبان الرياضية", city: "الباحة", street: "المندق"),
    SaudiAcademy(name: "أكاديمية جدة الاحترافية", city: "جدة", street: "الزهراء"),
    SaudiAcademy(name: "نسما البيانات الرقمية للترميه", city: "الخبر", street: "الصدفة"),
    SaudiAcademy(name: "أكاديمية يمامي الرياضية", city: "الرياض", street: "القيروان"),
    SaudiAcademy(name: "أكاديمية محترفين الغد المشرق", city: "الرياض", street: "طويق"),
]

let SAUDI_ACADEMY_NAMES: [String] = Array(Set(SAUDI_ACADEMIES.map { $0.name })).sorted()

let SAUDI_ACADEMY_CITIES: [String] = Array(Set(SAUDI_ACADEMIES.map { $0.city })).sorted()

func streetsForAcademy(_ name: String) -> [String] {
    Array(Set(SAUDI_ACADEMIES.filter { $0.name == name }.map { $0.street })).sorted()
}

func streetsForCity(_ city: String) -> [String] {
    Array(Set(SAUDI_ACADEMIES.filter { $0.city == city }.map { $0.street })).sorted()
}

func citiesForAcademy(_ name: String) -> [String] {
    Array(Set(SAUDI_ACADEMIES.filter { $0.name == name }.map { $0.city })).sorted()
}
